version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - "4566:4566"
    volumes:
      - "./localstack:/var/lib/localstack"
      - './init-scripts/create-buckets.sh:/etc/localstack/init/ready.d/init-create-buckets.sh:ro'
      - './init-scripts/create-queues.sh:/etc/localstack/init/ready.d/init-create-queues.sh:ro'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - localstack
      - db

volumes:
  db_data:
